data_path = '../../data'
era_path = data_path + '/era5'
era_path_eff = era_path + '/eff_ws'
windsim_data_path = data_path + '/windpower_simulation_input'
results_path = data_path + '/windpower_simulation'
